## XGBOOST

### Why XGBoost?
https://towardsdatascience.com/a-beginners-guide-to-xgboost-87f5d4c30ed7

https://towardsdatascience.com/https-medium-com-vishalmorde-xgboost-algorithm-long-she-may-rein-edd9f99be63d

Its fast and powerful :)

<img src="https://miro.medium.com/max/1920/1*U72CpSTnJ-XTjCisJqCqLg.jpeg"
     alt="Why XGBoost"/>

In [34]:
import xgboost as xgb
import pandas as pd
from sklearn.model_selection import train_test_split

# The output of multiple commands in a cell will be output at once.
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [45]:
# We start by importing the new data set
home_folder = '/Users/anthonymiyoro/Documents/code/DataTho/'

#Read dataset
train_modified = pd.read_csv(home_folder + 'train_modified.csv')
test_bundas = pd.read_csv(home_folder + 'bundas_test.csv')

### Split the data between train and test

We then remove the Item_ID feature as it does not correlate to Sales

In [46]:
train_modified = train_modified.drop('Item_ID', axis=1)

Our scikit learn package requires that the explanatory variables are stored seperately from the outcome variables.

In [47]:
rf_trainY = train_modified['Item_Store_Sales']
rf_trainX = train_modified.drop('Item_Store_Sales', axis=1)

In [48]:
X_train, X_test, y_train, y_test = train_test_split(rf_trainX, rf_trainY, test_size=0.2)

len(X_train)
len(X_test)
len(y_train)
len(y_test)

4890

1223

4890

1223

In [55]:
X_train.head(3)

Weight  Visibility  Max_Price  Store_Establishment_Year  FatContent_LF  \
1247   16.00    0.017548    48.3718                      2004              0   
2192   17.25    0.035058    91.6120                      2004              0   
6042    7.42    0.021662   187.7582                      2009              0   

      FatContent_Low Fat  FatContent_Regular  FatContent_low fat  \
1247                   0                   1                   0   
2192                   1                   0                   0   
6042                   0                   1                   0   

      FatContent_reg  Category_Baking Goods  ...  \
1247               0                      0  ...   
2192               0                      0  ...   
6042               0                      0  ...   

      Store_Type_Supermarket Type1  Store_Type_Supermarket Type2  \
1247                             1                             0   
2192                             1                             0   
6042                             0                             1   

      Store_Type_Supermarket Type3  Store_ID_OUT013  Store_ID_OUT018  \
1247                             0                0                0   
2192                             0                0                0   
6042                             0                0                1   

      Store_ID_OUT019  Store_ID_OUT027  Store_ID_OUT035  Store_ID_OUT046  \
1247                0                0                1                0   
2192                0                0                1                0   
6042                0                0                0                0   

      Store_ID_OUT049  
1247                0  
2192                0  
6042                0  

[3 rows x 42 columns]

In order for XGBoost to be able to use our data, we’ll need to transform it into a specific format that XGBoost can handle. 

That format is called DMatrix. We first transform our dataframe to a numoy array after which we can convert it to a DMatrix format. 

In [50]:
X_train.to_numpy()
X_test.to_numpy()
y_train.to_numpy()
y_test.to_numpy()

array([[1.60000000e+01, 1.75479580e-02, 4.83718000e+01, ...,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.72500000e+01, 3.50576880e-02, 9.16120000e+01, ...,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [7.42000000e+00, 2.16615270e-02, 1.87758200e+02, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [1.46000000e+01, 5.97328440e-02, 2.41253800e+02, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.60000000e+01, 1.72615327e-01, 1.54597200e+02, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.05000000e+01, 1.12785350e-02, 2.37024800e+02, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

array([[1.28576452e+01, 3.19466380e-02, 5.16008000e+01, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.50000000e+01, 4.90701830e-02, 6.19168000e+01, ...,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.28576452e+01, 6.17305200e-02, 1.59157800e+02, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [1.11500000e+01, 7.33542860e-02, 6.68142000e+01, ...,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.28576452e+01, 2.93417759e-01, 1.94613600e+02, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.57500000e+01, 1.35047260e-01, 9.85700000e+01, ...,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

array([ 614.5334,  279.636 , 2600.6148, ..., 5287.7836, 1869.5664,
       5451.5704])

array([1821.6288,  767.0016,  160.4578, ..., 2372.9112,  583.2408,
       2496.75  ])

In [52]:
D_train = xgb.DMatrix(X_train, label=y_train)
D_test = xgb.DMatrix(X_test, label=y_test)

/usr/local/lib/python3.7/site-packages/xgboost/core.py:587: FutureWarning: Series.base is deprecated and will be removed in a future version
  if getattr(data, 'base', None) is not None and \


We then define the parameters of our XGBoost model as shown below:

We use eta to prevent overfitting in our ensemble model as shown below: https://towardsdatascience.com/a-beginners-guide-to-xgboost-87f5d4c30ed7

In [58]:
param = {
    'eta': 0.3, 
    'max_depth': 3,  
    'objective': 'multi:softprob',  
    'num_class': 43} 

steps = 20  # The number of training iterations

We now train the model as shown below:

In [59]:
model = xgb.train(param, D_train, steps)

XGBoostError: [14:04:45] src/objective/multiclass_obj.cu:110: SoftmaxMultiClassObj: label must be in [0, num_class).
Stack trace:
  [bt] (0) 1   libxgboost.dylib                    0x0000000113cec579 dmlc::LogMessageFatal::~LogMessageFatal() + 57
  [bt] (1) 2   libxgboost.dylib                    0x0000000113d70edd xgboost::obj::SoftmaxMultiClassObj::GetGradient(xgboost::HostDeviceVector<float> const&, xgboost::MetaInfo const&, int, xgboost::HostDeviceVector<xgboost::detail::GradientPairInternal<float> >*) + 1629
  [bt] (2) 3   libxgboost.dylib                    0x0000000113ce87ef xgboost::LearnerImpl::UpdateOneIter(int, xgboost::DMatrix*) + 1311
  [bt] (3) 4   libxgboost.dylib                    0x0000000113d07314 XGBoosterUpdateOneIter + 180
  [bt] (4) 5   _ctypes.cpython-37m-darwin.so       0x0000000101f79377 ffi_call_unix64 + 79
  [bt] (5) 6   ???                                 0x00007ffeef486eb0 0x0 + 140732912922288

